driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm
  elevated: true

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  #
  # The following (private) boxes are shared via Atlas. Please note this
  # requires adding your Atlas account to the `Chef` org and will
  # require a `vagrant login`.
  #

  - name: windows-2008r2 # private
    driver_config:
      box: chef/windows-server-2008r2-standard
  - name: windows-server-2012r2-standard
    driver:
      box: chef/windows-server-2012r2-standard # private

suites:
  - name: default
    run_list:
      - recipe[wix::default]