driver:
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  #
  # The following (private) boxes are shared via Atlas. Please note this
  # requires adding your Atlas account to the `Chef` org and will
  # require a `vagrant login`.
  #
  # The Mac OS X boxes are VMware only also. You can enable VMware Fusion
  # as the default provider by copying `.kitchen.local.yml.vmware.example`
  # over to `.kitchen.local.yml`.
  #
  - name: windows-server-2012r2-standard
    driver:
      box: chef/windows-server-2012r2-standard # private

suites:
  - name: default
    run_list:
      - recipe[wix::default]
